# Generated by Django 6.0.2 on 2026-02-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_system_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
